
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-zones - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h2>Post 3: The Benefits of Using Next.js Zones</h2>
<p>Next.js zones are a powerful feature that can help you manage complex projects and optimize performance. In this blog post, we'll explore the benefits of using Next.js zones, including how they can help you scale your project and apply unique configurations to different parts of your website.</p>

  <Link href="/">Go back to the list</Link>
        </div>
      </main>
    </>
  )
}
