
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-zones - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h2>Post 5: How to Optimize Your Next.js App for SEO</h2>
<p>Optimizing your Next.js app for search engines is essential if you want to drive more traffic to your website. In this blog post, we'll share our top tips for optimizing your Next.js app for SEO, including how to use server-side rendering and how to structure your content for maximum search engine visibility.</p>
  <Link href="/">Go back to the list</Link>
        </div>
      </main>
    </>
  )
}
