
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-zones - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h2>Post 1: How to Build a Next.js App from Scratch</h2>
<p>In this blog post, we'll walk you through the process of building a simple Next.js app from scratch. We'll cover everything from setting up your development environment to deploying your app to the cloud. Whether you're new to Next.js or a seasoned developer, this post has something for everyone.</p>

  <Link href="/">Go back to the list</Link>
        </div>
      </main>
    </>
  )
}
