
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-zones - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h2>Post 4: Building a Scalable E-commerce Store with Next.js</h2>
<p>Building a scalable e-commerce store can be a challenging task, but Next.js can help make the process much easier. In this blog post, we'll show you how to build an e-commerce store with Next.js, including how to handle product listings, shopping carts, and payments.</p>

  <Link href="/">Go back to the list</Link>
        </div>
      </main>
    </>
  )
}
