
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-zones - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h2>Post 2: 10 Tips for Writing Clean and Maintainable Code</h2>
<p>Writing clean and maintainable code is essential for any project, but it can be challenging to know where to start. In this blog post, we'll share our top 10 tips for writing clean and maintainable code. We'll cover everything from naming conventions to code structure, so you can start writing better code today.</p>
  <Link href="/">Go back to the list</Link>
        </div>
      </main>
    </>
  )
}
