import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Main site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Welcome to the main site!</h1>
          <p>Learn more about it!</p>
            <ol>
              <li><Link href="/about">About the site</Link></li>
              <li><Link href="/blog">Read our blog</Link></li>
            </ol>
        </div>
      </main>
    </>
  )
}
